{% set name = "brainglobe-atlasapi" %}
{% set version = "2.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/brainglobe-atlasapi-{{ version }}.tar.gz
  sha256: ec78c7a8764ecb100281f5191ddf3f7e6fa40992ddcea194fde66a8ae2d6488b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=45
    - wheel
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.9
    - brainglobe-space >=1.0.0
    - click
    - loguru
    - meshio
    - numpy
    - pandas
    - pyarrow
    - pymcubes
    - requests
    - rich >=9.0.0
    - simpleitk
    - tifffile
    - tqdm >=4.46.1
    - treelib
    - vedo
    - vtk
    - xmltodict

test:
  imports:
    - brainglobe_atlasapi
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/brainglobe/brainglobe-atlasapi
  summary: A lightweight python module to interact with and generate atlases for systems neuroscience.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - willGraham01
    - adamltyson
    - alessandrofelder
