{% set python_min = "3.12" %}
{% set name = "brainglobe-atlasapi" %}
{% set version = "3.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 5d3531309dfe0e437467b0250d0e3e049e48c810f0903c97b976ff5b8f6a416c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=45
    - wheel
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - aiobotocore >=3.6.0
    - brainglobe-space >=1.0.0
    - click
    - dask-core
    - DracoPy !=2.1.0
    - fsspec
    - meshio
    - ngff_zarr >=0.37.0
    - numpy
    - pandas
    - pyarrow
    - requests
    - rich >=9.0.0
    - s3fs
    - tifffile >=2018.11.6
    - tqdm >=4.46.1
    - treelib
    - zarr >3

test:
  imports:
    - brainglobe_atlasapi
  commands:
    - pip check
    - brainglobe --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/brainglobe/brainglobe-atlasapi
  summary: A lightweight python module to interact with and generate atlases for systems neuroscience.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - IgorTatarnikov
    - adamltyson
    - alessandrofelder
